services:
  - type: web
    name: quickhomeservicefinder
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn quickhomeservicefinder.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quickhomeservicefinder.settings
