# Generated by Django 4.1.4 on 2022-12-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('dp', models.ImageField(upload_to='photos')),
                ('role', models.CharField(choices=[('0', 'ADMIN'), ('1', 'USER')], max_length=10)),
                ('status', models.CharField(choices=[('0', 'INACTIVE'), ('1', 'ACTIVE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=30)),
                ('service_description', models.TextField()),
                ('service_price', models.IntegerField()),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.login_table')),
                ('serviceperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.service')),
            ],
        ),
        migrations.CreateModel(
            name='detail_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.area_table')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.city')),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.login_table')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.state'),
        ),
        migrations.CreateModel(
            name='booking_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.login_table')),
                ('serviceperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.service')),
            ],
        ),
        migrations.AddField(
            model_name='area_table',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.city'),
        ),
        migrations.AddField(
            model_name='area_table',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeservicer.state'),
        ),
    ]
