# Generated by Django 4.1.7 on 2023-02-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0002_login_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_table',
            name='status',
        ),
        migrations.AlterField(
            model_name='login_table',
            name='role',
            field=models.CharField(choices=[('provider', 'provider'), ('user', 'user')], max_length=10),
        ),
    ]
