# Generated by Django 4.1.7 on 2023-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0003_remove_login_table_status_alter_login_table_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category_name', models.CharField(max_length=25)),
            ],
        ),
    ]
