# Generated by Django 4.1.7 on 2023-02-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0004_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homeservicer.service_category'),
        ),
    ]
