# Generated by Django 4.1.7 on 2023-02-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0005_service_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_category',
            name='service_category_photo',
            field=models.ImageField(default='pl.jpg', upload_to=''),
        ),
    ]
