# Generated by Django 4.1.7 on 2023-02-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0006_service_category_service_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
    ]
