# Generated by Django 4.1.7 on 2023-02-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0007_remove_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_service',
            name='ubr_status',
            field=models.CharField(choices=[('Waiting for Confirmation', 'Waiting for Confirmation'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Waiting for Confirmation', max_length=50),
        ),
    ]
