# Generated by Django 4.1.7 on 2023-02-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0008_booking_service_ubr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_service',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking_service',
            name='show_approve_button',
            field=models.BooleanField(default=True),
        ),
    ]
