# Generated by Django 4.1.7 on 2023-02-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0009_booking_service_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='l_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='serviceperson',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
