# Generated by Django 5.0 on 2024-03-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0010_remove_feedback_l_id_remove_feedback_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_service',
            name='paymethod',
            field=models.CharField(choices=[('paynow', 'Online'), ('cash', 'Offline')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
