# Generated by Django 5.0 on 2024-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0011_booking_service_paymethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_service',
            name='paymethod',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Offline')], max_length=50),
        ),
    ]
