# Generated by Django 4.2.3 on 2024-03-24 08:22

from django.db import migrations, models
import homeservicer.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0012_alter_booking_service_paymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_photo',
            field=models.ImageField(default='null', upload_to=homeservicer.models.upload_to_profile),
        ),
    ]
