# Generated by Django 4.2.3 on 2024-03-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0013_service_service_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_table',
            name='area_id',
        ),
        migrations.AlterField(
            model_name='detail_table',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail_table',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=200),
        ),
    ]
