# Generated by Django 4.2.3 on 2024-03-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0014_remove_detail_table_area_id_alter_detail_table_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_table',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
