# Generated by Django 4.2.3 on 2024-03-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0018_alter_detail_table_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_table',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
