# Generated by Django 4.2.3 on 2024-03-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0022_alter_detail_table_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_table',
            name='pincode',
        ),
        migrations.AddField(
            model_name='booking_service',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking_service',
            name='sdate',
            field=models.DateField(null=True),
        ),
    ]
