# Generated by Django 4.2.3 on 2024-03-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0023_remove_detail_table_pincode_booking_service_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_table',
            name='area_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeservicer.area_table'),
        ),
        migrations.AlterField(
            model_name='detail_table',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeservicer.city'),
        ),
        migrations.AlterField(
            model_name='detail_table',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homeservicer.state'),
        ),
    ]
