# Generated by Django 5.0.2 on 2024-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0024_detail_table_area_id_alter_detail_table_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_table',
            name='provideraadhaar',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
