# Generated by Django 5.0.2 on 2024-04-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0025_detail_table_provideraadhaar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail_table',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='detail_table',
            old_name='state',
            new_name='state_id',
        ),
    ]
