# Generated by Django 5.0 on 2024-04-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0026_rename_city_detail_table_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
