# Generated by Django 5.0 on 2024-04-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0027_feedback_contact_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
