# Generated by Django 5.1.4 on 2025-04-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeservicer', '0028_feedback_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_service',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
